### PR TITLE
build tweaks & minor fixes

### PR DESCRIPTION
**Pull request by barak**
if you don't want the build tweaks (which makes it build painlessly and with maximum parallelism for me!) the others are I think pretty unobjectionable.

### CODE REVIEW

**Comment by yhzhm** [comment]
来自杨海中的自动回复邮件。
您好，来信已收到，我会尽快处理。

**Comment by barak** [comment]
תודה רבה.

**Comment by liuxinyu95** [comment]
thanks. 

I like the idea to simplify the build process.

**Comment by liuxinyu95** [comment]
Past from the revert comment:

Although it works for the whole book, I found it broken the following:
1. build for separated chapters;
2. build for separated example code

I'll next merge the change for URL, quotes etc, but the build changes need more review.

**Comment by barak** [comment]
I'll take a look at building separated chapters & example code to work with latexmk. Should be straightforward.

**Comment by liuxinyu95** [comment]
I cherry-picked all the changes excepted for the build process improvement. I'll next take your idea, and maintain each chapter/example program can be build standalone.

**Comment by barak** [comment]
Oops, just noticed your force-push! I already did that rebase, and am doing final touches on rewriting the build system to also handle individual chapters.

Will rebase onto your forced-push...

**Pull request merged**
