### PR TITLE
added Stack

### PR DESCRIPTION
**Pull request by sujalgera01**
A basic STACK code by means of which every complex problem can be easily solved.

### CODE REVIEW

**Comment by liuxinyu95** [comment]
Hi,

Thanks for contribute an example stack implementation.  Basically, the example programs provided along with the book serve to explain the content. Recently, we moved the list to the first chapter. Stack can be covered as a use case of list/array, or any sequence based data structure. Because of this, there is no dedicated chapter about stack.

Hopefully you understand this consideration.

Thanks.
--
Xinyu

**Comment by sujalgera01** [comment]
Hello!!
I understood what you said. Can I know what should I contribute to your
repo that will be useful to others an d will be acceptable too because I
want to make an assignment for my college where I want to show that I
contributed in the open source. My teacher will check all those what I will
be pushing in the repo.
This is my assignment and for this marks will be awarded. So, can you help
me out like where I should contribute then?
Thanks

**Comment by liuxinyu95** [comment]
Hi,

For every chapter, we haven't provided answers yet. Feel free to provide your answers (example programs) to any exercise.
When adding answers, you can create a sub-folder under the `src` folder. for e.g. 
`/datastruct/tree/red-black-tree/src/exercise`

Please also add test cases to verify the answer.

Thanks.
Xinyu

**Comment by sujalgera01** [comment]
Ok, I got you.
Also, Can I make a new folder with 'PHP' where I can upload my project
constantly. I will upload the components of my project slowly so that my
teacher will be agreed seeing that i worked for some days on the project
and repo looks awesome. Please let me know.
Thanks

**Comment by liuxinyu95** [comment]
Hi,

If that's the case, the recommended practice is to clone and create your own branch. This OSS project is an open book about algorithms in both functional and imperative approach. We tried our best to minimize the background knowledges about programing languages. As of 2020, we managed limit the example languages only within Haskell, C/C++, Python in main book context. From 2021, we started further minimizing it to only 2: Haskell and a virtual imperative language.

As such, we'll not accept new programing language example programs to the main-line.

Regards.
Xinyu

**Comment by sujalgera01** [comment]
Thank you for the clarification.

**Pull request closed without merging**
